# Generated by Django 3.2.9 on 2022-02-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_mystory_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='username',
        ),
    ]
