# Generated by Django 3.2.9 on 2022-02-18 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_userreg_groups_userreg_user_permissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='room',
            new_name='mystory',
        ),
    ]
