# Generated by Django 3.2.9 on 2022-02-28 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_rename_user_comment_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='username',
            new_name='user',
        ),
    ]
